### ISSUE TITLE
Switching node versions changes encryption output

### ISSUE THREAD

**Issue by martelli** [igarape/copcast-server#62]
When switching the node version, the cryptography test executed at the beginning of the server fails.
We must investigate whats actually causing this.

**Comment by dborkan** [comment]
Just curious, which tests are these?  I tried ```grunt test``` in the webrecorder branch of copcast-server, first with node v0.12.14, then v5.0.0, then v0.12.14 again, and it passed each time.

**Comment by martelli** [comment]
During startup, we collect the system encryption password. To make sure it
is the as previously informed, we try to decrypt a small amount of data.
Curiously, the crypto.pbkdf2Sync() function behaves differently, depending
on the version (0.10 vs. 4+) and thus the encryption is affected.

**Comment by dborkan** [comment]
Ah OK - you mean this error here https://github.com/igarape/copcast-server/blob/webrecorder/lib/crypto/index.js#L36 right?  I think I was confused because I was thinking it was a problem in ```grunt test```

Also on my machine I've tried switching different node versions, and I see that, v0.12.14 (what I normally run on my machine), v0.11.16, v4.0.0, and v5.0.0 all work when I switch between them, but when I use v0.10.45 it fails with that ```Invalid master key``` error

**Comment by dborkan** [comment]
I figured out the root cause here (actually found it on https://github.com/nodejs/node/issues/4317).

In Node 0.10 and older, ```crypto.pbkdf2Sync``` actually only supported 4 arguments (password, salt, iterations, keylen), and the digest used was always 'sha1'.  But in Node 0.11 and later, the 5th digest parameter was added.

So if we are running the server on Node 0.10, even though our calls to ```crypto.pbkdf2Sync``` say 'sha256', we are actually creating (then encrypting with) a key using 'sha1'.  When we upgrade Node versions to 0.11 or later, the key then really uses that 'sha256' parameter so it no longer can decrypt the old data.

So if we change that parameter in the code to 'sha1', we make it past the verification check.  Maybe this is sufficient and we don't have to update the data stored in the DB?  Also I do see this code also using 'SHA256', not sure if it has to be changed too: https://github.com/igarape/copcast-server/blob/webrecorder/lib/signing/index.js#L18 ?

**Comment by martelli** [comment]
Great!

As it's not used to store the any passwords (we only save it into the
config file for development purposes), I think we are fine to keep using
SHA1.

https://crackstation.net/hashing-security.htm

"Even though there are no cryptographic attacks on MD5 or SHA1 that make
their hashes easier to crack, they are old and are widely considered
(somewhat incorrectly) to be inadequate for password storage. So I don't
recommend using them. An exception to this rule is PBKDF2, which is
frequently implemented using SHA1 as the underlying hash function."

Cheers,

</Leandro>
